account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "account"

urlpatterns = [
    path(
        "signup/",
        views.SignUpView.as_view(),
        name="signup"
    ),
    path(
        "signup-success/",
        views.SignUpSuccessView.as_view(),
        name="signup_success"
    ),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="login.html"),
        name="login"
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="logout.html"),
        name="logout"
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="logout.html"),
        name="logout"
    ),
    path(
        "user-data/<int:pk>",
        views.UserUpdate.as_view(),
        name="user_update"
    ),
    path(
        "profile/",
        views.UserDetailCreate.as_view(),
        name="create_feedback_rule"
    ),
    path(
        "profile/<int:detail_num>",
        views.UserDetailCreate.as_view(),
        name="create_feedback_rule"
    ),
    path(
        "profile-edit/<int:pk>",
        views.UserDetailUpdate.as_view(),
        name="update_feedback_rule"
    ),
    path(
        "mypage/<int:pk>",
        views.CustomUserDetailView.as_view(),
        name="mypage"
    ),
    
]

feedback/urls.py
from django.urls import path

from . import views

app_name = "feedback"

urlpatterns = [
    path('add-feedback/<int:task_id>', views.FeedbackCreateView.as_view(), name="feedback_add"),
    path('reply/<int:task_id>/<int:feedback_id>', views.FeedbackReplyView.as_view(), name="reply"),
    path('help/<int:pk>', views.HelpView.as_view(), name="help"),
]

good_feedback/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("project.urls")),
    path("account/", include("account.urls")),
    path("feedback/", include("feedback.urls")),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

project/urls.py
from django.urls import path

from . import views

app_name = "project"

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('new-project-create/', views.CreateProjectView.as_view(), name="create_project"),
    path('new-project-propose/<int:pk>', views.ProposeProjectView.as_view(), name="propose_project"),
    path('new-project/feedback-set/<int:pk>', views.SetFeedbackView.as_view(), name="feedback_set"),
    path('project-list/', views.ProjectListView.as_view(), name="project_list"),
    path('project/<int:pk>', views.ProjectDetailView.as_view(), name="project_detail"),
    path('new-project/<int:pk>', views.CreateProjectSuccessView.as_view(), name="create_project_done"),
    path('project-update/<int:pk>', views.ProjectUpdateView.as_view(), name="project_update"),
    path('project-done/<int:pk>', views.ProjectDoneView.as_view(), name="project_done"),
    path('project-finish', views.ProjectDoneSuccessView.as_view(), name="project_done_success"),
    path('add-task/<int:pk>', views.AddTaskView.as_view(), name="add_task"),
    path('task-list/<int:pk>', views.TaskListView.as_view(), name="task_list"),
    path('task-detail/<int:pk>', views.TaskDetailView.as_view(), name="task_detail"),
    path('task-edit/<int:pk>', views.TaskEditView.as_view(), name="task_edit"),
    path('task-delete/<int:pk>', views.TaskDeleteView.as_view(), name="task_delete"),
    path('add-todo/<int:pk>/<int:project_id>', views.ToDoCreateView.as_view(), name="add_todo"),
    path('todo-check/<int:pk>', views.ToDoDoneView.as_view(), name="todo_checked"),
    # path('todo-delete/<int:pk>', views.ToDoDeleteView.as_view(), name="todo_delete"),

    path('todo-done/<int:pk>', views.todo_done, name="todo_done"),
    path('todo-delete/<int:pk>', views.todo_delete, name="todo_delete"),

    path('about', views.AboutUsView.as_view(), name="about_us"),
    # path('project/<int:pk>/done', views.done_todo, name="done_todo"),
]

project/models.py
from django.db import models
import markdown

from account.models import CustomUser, UserDetail

class Project(models.Model):
    title = models.CharField(
        verbose_name="プロジェクトのタイトル",
        max_length=30,
    )
    about = models.TextField(
        verbose_name="このプロジェクトについて"
    )
    purpose = models.TextField(
        verbose_name="このプロジェクトで実現したいこと",
        null=True
    )
    deadline_datetime = models.DateTimeField(
        verbose_name="締め切り日時",
        # auto_now_add=False  # ここないからエラーの可能性
    )
    reference_image1 = models.ImageField(
        verbose_name="参考画像1",
        upload_to="references",
        blank=True,
        null=True,
    )
    reference_image2 = models.ImageField(
        verbose_name="参考画像2",
        upload_to="references",
        blank=True,
        null=True,
    )
    reference_image3 = models.ImageField(
        verbose_name="参考画像3",
        upload_to="references",
        blank=True,
        null=True,
    )
    reference_movie1 = models.FileField(
        verbose_name="参考動画1",
        upload_to="references",
        blank=True,
        null=True,
    )
    reference_movie2 = models.FileField(
        verbose_name="参考動画2",
        upload_to="references",
        blank=True,
        null=True,
    )
    reference_movie3 = models.FileField(
        verbose_name="参考動画3",
        upload_to="references",
        blank=True,
        null=True,
    )
    reference_music1 = models.FileField(
        verbose_name="参考音源1",
        upload_to="references",
        blank=True,
        null=True,
    )
    reference_music2 = models.FileField(
        verbose_name="参考音源2",
        upload_to="references",
        blank=True,
        null=True,
    )
    reference_music3 = models.FileField(
        verbose_name="参考音源3",
        upload_to="references",
        blank=True,
        null=True,
    )
    reference_url1 = models.URLField(
        verbose_name="参考URL1",
        blank=True,
        null=True,
    )
    reference_url2 = models.URLField(
        verbose_name="参考URL2",
        blank=True,
        null=True,
    )
    reference_url3 = models.URLField(
        verbose_name="参考URL3",
        blank=True,
        null=True,
    )

    created_at = models.DateTimeField(
        verbose_name="プロジェクトを登録した日時",
        auto_now_add=True,
    )
    updated_at = models.DateTimeField(
        verbose_name="プロジェクトの詳細を更新した時間",
        auto_now=True,
    )
    orderer_user = models.ForeignKey(
        CustomUser,
        verbose_name="発注者",
        on_delete=models.PROTECT,
        related_name="orderer_user",
    )
    contractor_user = models.ForeignKey(
        CustomUser,
        verbose_name="受注者",
        on_delete=models.PROTECT,
        related_name="contractor_user",
        
    )
    orderer_users = models.ManyToManyField(
        CustomUser,
        verbose_name="発注者のサポーター",
        blank=True,
        related_name="orderer_users",
    )
    contractor_users = models.ManyToManyField(
        CustomUser,
        verbose_name="受注者のサポーター",
        blank=True,
        related_name="contractor_users",
    )
    created_user = models.ForeignKey(
        CustomUser,
        verbose_name="プロジェクトの作成者",
        on_delete=models.PROTECT,
        related_name="created_user"
    )
    is_done = models.BooleanField(
        default=False,
        help_text="プロジェクトが完了したらTrue"
    )
    is_accepted = models.BooleanField(
        default=False,
        help_text="プロジェクトを確認してもらえたらTrue"
    )
    feedback_rule = models.ForeignKey(
        UserDetail,
        verbose_name="受注した人が設定したフィードバックルール",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )

    def markdown_to_html(self):
        """Markdown を HTML に変換して出力
        さらに拡張機能を使用して目次を自動生成する"""
        md = markdown.Markdown(
            extensions=['extra', 'admonition', 'sane_lists', 'toc'])
        html = md.convert(self.about)
        return html

    def __str__(self):
        return self.title


class Task(models.Model):
    title = models.CharField(
        verbose_name="タイトル",
        max_length=30,
    )
    content = models.TextField(
        verbose_name="本文"
    )
    deadline_datetime = models.DateTimeField(
        verbose_name="締め切り日時",
        # auto_now_add=False  # 書いていないからエラー出るかも
    )
    added_at = models.DateTimeField(
        verbose_name="タスクを追加した日時",
        auto_now_add=True,
    )
    updated_at = models.DateTimeField(
        verbose_name="タスクを更新した日時",
        auto_now=True,
        null=True,
        blank=True,
    )
    project = models.ForeignKey(
        Project,
        verbose_name="プロジェクト",
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.title
    

class ToDo(models.Model):
    title = models.CharField(
        verbose_name="ToDoのタイトル",
        max_length=100

    )
    added_at = models.DateTimeField(
        verbose_name="ToDoを追加した日時",
        auto_now_add=True,
    )
    task = models.ForeignKey(
        Task,
        verbose_name="関連するタスク",
        on_delete=models.CASCADE,
    )
    is_done = models.BooleanField(
        default=False,
        help_text="todoを完了させたらTrue"
    )
    project = models.ForeignKey(
        Project,
        verbose_name="関連するプロジェクト",
        on_delete=models.CASCADE,
    )
    def __str__(self):
        return self.title

feedback/forms.py
from django.forms import ModelForm

from .models import Feedback

class FeedbackForm(ModelForm):
    class Meta:
        model = Feedback
        exclude = ("self", "task", "user")

project/forms.py
from django import forms

from .models import Project, Task, ToDo
from account.models import CustomUser

class CreateProjectForm(forms.ModelForm):

    deadline_datetime = forms.SplitDateTimeField(
        label="締め切り日時",
        widget=forms.SplitDateTimeWidget(
            date_attrs={"type":"date"},
            time_attrs={"type":"time"}
        )
    )

    
    contractor_user = forms.ModelChoiceField(
        CustomUser.objects,
        to_field_name='username',
        label='受注者のユーザーID',
        empty_label='入力してください',
        widget=forms.TextInput,
        error_messages={'invalid_choice':'このユーザーID存在しません'}
    )
    supporter = forms.CharField(
        label="あなたのサポーター",
        max_length=255,
        required=False
    )

    class Meta:
        model = Project
        fields = [
            "title",
            "about",
            "deadline_datetime",
            "purpose",
            # "time",
            # "date",

            # "created_at",
            # "updated_at",
            # "orderer_user",
            "contractor_user",
            # "orderer_users",
            # "contractor_users",
            "supporter",
            "reference_image1",
            "reference_image2",
            "reference_image3",
            "reference_movie1",
            "reference_movie2",
            "reference_movie3",
            "reference_music1",
            "reference_music2",
            "reference_music3",
            "reference_url1",
            "reference_url2",
            "reference_url3",
        ]

    def clean_supporter(self):
        supporter = self.cleaned_data.get("supporter")
        supporters_list = supporter.split(",")
        return supporters_list



class UpdateProjectForm(forms.ModelForm):
    date = forms.DateField(label="日にち", initial="2023/12/24")
    time = forms.TimeField(label="時間", initial="12:00")
    deadline_datetime = forms.DateTimeField(required=False)


    class Meta:
        model = Project
        fields = [
            "title",
            "about",
            "deadline_datetime",
            "time",
            "date",
            # "reference_image1",
            # "reference_image2",
            # "reference_image3",
            # "reference_movie1",
            # "reference_movie2",
            # "reference_movie3",
            # "reference_music1",
            # "reference_music2",
            # "reference_music3",
            # "reference_url1",
            # "reference_url2",
            # "reference_url3",
            # # "created_at",
            # # "updated_at",
            # # "orderer_user",
            # "contractor_user",
            # "orderer_users",
            # # "contractor_users",

        ]




class ProjectProposeForm(forms.ModelForm):
    c_supporter = forms.CharField(
        label="あなたのサポーター",
        max_length=255,
        required=False
    )
    class Meta:
        model = Project
        fields = [
            "is_accepted",
            "c_supporter",
        ]

    def clean_c_supporter(self):
        c_supporter = self.cleaned_data.get("c_supporter")
        c_supporters_list = c_supporter.split(",")
        return c_supporters_list







class AddTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = (
            'project',
            "updated_at",
        )

class ToDoCreateForm(forms.ModelForm):
    class Meta:
        model = ToDo
        # fields = "__all__"
        exclude = ("project", "task", "is_done")

feedback/views.py
from django.shortcuts import render

from django.views.generic import TemplateView, CreateView, ListView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.db.models import Max

from .models import Feedback
from .forms import FeedbackForm

from project.models import Task

class FeedbackCreateView(CreateView):
    template_name = "add_feedback.html"
    form_class = FeedbackForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["task"] = Task.objects.get(id=self.kwargs["task_id"])
        print(context["task"].project)
        return context

    def get_success_url(self):
        return reverse_lazy("project:project_detail", kwargs={"pk": self.object.task.project.pk})

    

    def form_valid(self, form):
        feedback = form.save(commit=False)
        feedback.user = self.request.user
        feedback.task_id = self.kwargs["task_id"]
        feedback.save()
        return super().form_valid(form)
    

class FeedbackReplyView(CreateView):
    template_name = "add_feedback.html"
    form_class = FeedbackForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["reply_to"] = Feedback.objects.get(id=self.kwargs["feedback_id"])
        context["task"] = Task.objects.get(id=self.kwargs["task_id"])

        return context
    

    def get_success_url(self):
        return reverse_lazy("project:project_detail", kwargs={"pk": self.object.task.project.pk})
    
    

    def form_valid(self, form):
        feedback = form.save(commit=False)

        feedback.user = self.request.user
        feedback.task_id = self.kwargs["task_id"]
        feedback.self_id = self.kwargs["feedback_id"]
        feedback.save()
        return super().form_valid(form)
    


class HelpView(DetailView):
    template_name = "help.html"
    model = Feedback



project/templates/_form.html
{% load widget_tweaks %}


<form action="" method="post">
  {% csrf_token %}
  {% for field in form %}
  
  <div class="mb-3">
    <label class="form-label" for="{{field.id_for_label}}">{{field.label}}</label>
    {% render_field field class="form-control" %}
    {{field.errors}}
    {% for error in field.errors %}
    <p>{{error}}</p>
    {% endfor %}
  </div>
  {% endfor %}

  <button type="submit" class="btn btn-primary">{{button_message}}</button>
  
</form>

project/templates/about_us.html
{% extends "base.html" %}


{% block contents %}
<div class="container">


  <p>詳しい解説をここに書きます</p>
</div>

{% endblock %}

project/templates/add_todo.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block contents %}


<div class="container">

  <h5 class="pb-1 border-bottom">タスク : {{task}}</h5>

  <form action="" method="post">
    {% csrf_token %}
    {% for field in form %}
    
    <div class="mb-3">
      <label class="form-label" for="{{field.id_for_label}}">{{field.label}}</label>
      {% render_field field class="form-control" %}
      {{field.errors}}
      {% for error in field.errors %}
      <p>{{error}}</p>
      {% endfor %}
    </div>
    {% endfor %}

    <button type="submit" class="btn btn-primary">追加する</button>
    
  </form>

</div>

{% endblock %}

project/templates/introduction.html
<div class="container">
  <div class="card py-3 px-3 pb-2">

    <h4 class="border-bottom">より良いクリエイティブな活動のために</h4>
    <p>創作活動において、仕事相手や仲間とのコミュニケーションで<br>
    <p>こうしたいイメージはあるのに、うまく伝わらない、伝わっていない、という経験はありませんか？</p>
    <p>また、フィードバックはあるけど、どういうことか掴みにくい。。。という経験はありませんか？</p>
    <br>
    <p><strong>ナイスフィードバック</strong>では、そんな悩みを抱えている制作者の皆様のお手伝いを目指しています！</p>
    <p>より良いクリエイティブな活動の為に、ぜひご活用ください！</p>
  
    <p><a href="{% url "project:about_us" %}">もっと詳しく知りたい方はこちら</a></p>
    <p><a href="{% url "account:signup" %}">ユーザー登録はこちら</a></p>
  </div>




  
</div>

project/templates/new_project.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block contents %}

<div class="container">



  <h5 class="pb-1 border-bottom">新しいプロジェクトが作成されました : {{project.title}}</h5>
    

  {% for field in form %}

  {% if field == form.deadline_datetime %}
    <div class="mb-3 row">
      <label class="form-label" for="">締め切り日時</label>
      <div class="col">
        
        <input type="date" name="deadline_datetime_0" class="form-control" required="" id="id_deadline_datetime_0">
      </div>
      <div class="col">
        <input type="time" name="deadline_datetime_1" class="form-control" required="" id="id_deadline_datetime_1">
      </div>
    </div>

  {% else %}

    <div class="mb-3">
      <label class="form-label" for="{{field.id_for_label}}">{{field.label}}</label>
      {% render_field field class="form-control-plaintext" readonly="readonly" %}
    </div>

    {% if field == form.supporter %}
    <div class="mb-3">

      <button class="btn btn-secondary text-white" type="button" data-bs-toggle="collapse" data-bs-target="#collapseReference" aria-expanded="false" aria-controls="collapseReference">
        ＋参考資料をアップロードする
      </button>
    </div>
    <div class="collapse" id="collapseReference">

    {% elif field == form.reference_url3 %}
    </div>
    {% endif %}


  {% endif %}


  {% endfor %}
    
    
    <a href="{% url "project:project_list" %}">{{request.user}}さんが作成したプロジェクト一覧はこちら</a>
</div>
{% endblock %}

project/templates/project_done_success.html
<div class="container">


  <h3>お疲れさまでした</h3>
  <a href="{% url "project:index" %}">マイページに戻る</a>
</div>

project/templates/propose_project.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block contents %}

<div class="container">

  <div class="d-flex border-bottom mb-2">
    <h5 class="mb-1 ps-3">
      お仕事依頼
    </h5>
  </div>

  <div class="ps-3">
    <p>下記の内容で、お仕事の依頼が届いています。<br>
      内容を確認して、フィードバックルールの設定をしましょう！
    </p>
  </div>


  <div class="card mb-3 mx-1 py-3 px-3 ">
    <h5>プロジェクト : {{project.title}}</h5>
  
    <h6>依頼者 : {{project.orderer_user}}さん</h6>
    <h6>概要 : </h6>
    <div>
      {{project.about|linebreaks}}
    </div>
    
    <h6>締切日時 : {{project.deadline_datetime}}</h6>
    
    {% if project.purpose %}
    <h6>このプロジェクトの目標 : </h6>
    <div>
      {{project.purpose|linebreaks}}
    </div>
    {% endif %}
  
    <a href="">参考資料を確認する</a>
  </div>

  <div class="ms-3">
    <form action="" method="post">
      <p>以上の内容を確認されましたらチェックをつけてください。</p>
      {% csrf_token %}
  
      <div class="mb-3">

        <input type="checkbox" class="form-check-input" name="is_accepted" id="id_is_accepted" class="">
        <label for="id_is_accepted" class="form-check-label">確認しました</label> 
      </div>
  
      <p>{{request.user}}さんのサポーターを設定する場合は、下記ボックスにユーザー名を入力してください。</p>
      <div>
        {% comment %} <label class="form-label" for="{{form.c_supporter.id_for_label}}">{{form.c_supporter.label}}</label> {% endcomment %}
        {% render_field form.c_supporter class="form-control" %}
      </div>

      <button type="submit" class="btn btn-primary mt-3" id="submitButton" disabled>フィードバックルールを設定画面に移る</button>
    </form>
  </div>
  
</div>

<script>
  // チェックボックスの状態が変わったら実行される関数
  $('#id_is_accepted').change(function () {
      // チェックボックスがチェックされているか確認
      if (this.checked) {
          // ボタンを有効化
          $('#submitButton').prop('disabled', false);
      } else {
          // ボタンを無効化
          $('#submitButton').prop('disabled', true);
      }
  });
</script>

{% endblock %}

project/templates/task_delete.html
{% extends "base.html" %}

{% block contents %}


<h1>
  ほんとに消してもよいですか？
</h1>

<form action="" method="post">
  {% csrf_token %}
  <button type="submit">はい</button>
  <a href="{% url "project:task_detail" object.pk %}">キャンセル</a>
</form>
{% endblock %}

project/templates/task_detail.html
{% extends "base.html" %}

{% block contents %}

<div class="container">

  <div class="card py-2 px-3 bg-white">

    <a href="{% url "project:project_detail" object.project.id %}">プロジェクト：{{object.project}}</a>

    <div class="border-bottom d-flex justify-content-between mb-2">
      <h5 class="mb-0" >タスク : {{object.title}}</h5>
    {% if request.user == object.project.orderer_user %}
      <a href="{% url "project:task_edit" object.pk %}" class="fs-6 fw-normal"><i class="bi bi-pencil"></i>編集する</a>
    {% endif %}
    </div>

    <p>{{object.content}}</p>
    
    <small>締め切り：{{object.deadline_datetime}}</small>
    <small>作成日時：{{object.added_at}}</small>
    <small>更新日時：{{object.updated_at}}</small>

    <div class="my-2">
      <a href="{% url "feedback:feedback_add" object.pk %}" >フィードバックを送る</a>
    </div>

    {% if feedbacks %}
    <ul>
      {% for feedback in feedbacks %}
      <li>{{feedback.comment}} <span>{{feedback.user}}</span> </li>
      {% endfor %}
    </ul>
    {% endif %}
    
    
    {% if request.user == object.project.contractor_user %}
    todoの一覧
      {% if todos %}

    <ul>
      {% for todo in todos %}
      <li>{{todo}}</li>
      {% endfor %}
    </ul>
      {% else %}
      todoはありません
      {% endif %}
    <a href="{% url "project:add_todo" object.pk object.project_id %}">ToDoを追加する</a>
    {% endif %}
    
    <a href="{% url "project:task_list" object.project_id %}">タスクの一覧を確認する</a>
  </div>
</div>
{% endblock %}

project/templates/task_edit.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block contents %}

<div class="container">



  <form action="" method="post">
  {% csrf_token %}
  {% for field in form %}
    
    {% comment %} {% if field == form.updated_at %} {% endcomment %}
    {% comment %} {% else %} {% endcomment %}
    <div class="mb-3">
      <label class="form-label" for="{{field.id_for_label}}">{{field.label}}</label>
      {% render_field field class="form-control" %}
      {{field.errors}}
      {% for error in field.errors %}
      <p>{{error}}</p>
      {% endfor %}
    </div>
    {% comment %} {% endif %} {% endcomment %}

  {% endfor %}
  
    <a href="{% url "project:task_detail" object.pk %}" class="btn btn-secondary">戻る</a>
    <button type="submit" class="btn btn-primary">{{button_message}}</button>
    <a href="{% url "project:task_delete" object.pk %}" class="btn btn-secondary {% if object.feedback_set %}disabled{% endif %} ">削除する</a>
    {% if object.feedback_set %}
    <small class="text-warning">フィードバックがついているので、タスクを削除することはできません</small>
    {% endif %}

    
  </form>
</div>


{% endblock %}

project/templates/task_list.html
{% extends "base.html" %}

{% block contents %}


<div class="container">

  <div class="card py-2 px-3 bg-white">

    <a href="{% url "project:project_detail" project.pk %}">プロジェクト：{{project}}</a>
    {{object_list.project}}
    <h5>タスク一覧</h5>

    <ul>
      {% for record in object_list %}
      <li>
        <a href="{% url "project:task_detail" record.pk %}">
          {{record}}
        </a>

      </li>
      {% endfor %}
    </ul>

  </div>

</div>

{% endblock %}

project/templates/update_project.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block contents %}

<div class="container">

<form action="" method="post">
  
  {% csrf_token %}
{% comment %} {{form}} {% endcomment %}


{% for field in form %}
{% if field == form.time or field == form.date or field == form.deadline_datetime %}


{% else %}



<div class="mb-3">
  <label class="form-label" for="{{field.id_for_label}}">{{field.label}}</label>
  {% render_field field class="form-control" %}
  {{field.errors}}
  {% for error in field.errors %}
  <p>{{error}}</p>
  {% endfor %}
</div>
{% endif %}
{% endfor %}

<div class="mb-3">
  <div class="form-label">締切日時</div>
  <div class="row">
    <div class="col">
      <input class="form-control" type="date" name="date" required id="id_date" value="{{date}}">
    </div>
    <div class="col">
      <input class="form-control" type="time" name="time" required id="id_time" value="{{time}}" >
    </div>
  </div>
</div>
{{test}}
{% comment %} 

  <div class="mb-3">
    <label class="form-label" for="id_about">このプロジェクトについて</label>
    <textarea class="form-control" name="about" cols="40" rows="10" required id="id_about"></textarea>
  </div>

  
  <div class="mb-3">
    <label class="form-label" for="id_contractor_user">発注先ユーザー名</label>
    <input class="form-control" type="text" name="contractor_user" maxlength="30" required id="id_contractor_user">
  </div>

  <div class="mb-3">
    <label class="form-label" for="id_orderer_users">発注者のサポーター</label>
    <select name="orderer_users" id="id_orderer_users" multiple>
  <option value="1">admin</option>

  <option value="3">test</option>

  <option value="4">test2</option>

  <option value="5">test3</option>

</select>




  <div class="mb-3">
    <div class="form-label">締切日時</div>
    <div class="row">
      <div class="col">
        <input class="form-control" type="date" name="date" required id="id_date">
      </div>
      <div class="col">
        <input class="form-control" type="time" name="time" required id="id_time" >
      </div>
    </div>
  </div>



  <div class="mb-3">
    <label class="form-label" for="id_reference_image1">参考画像1</label>
    <input class="form-control" type="file" name="reference_image1" accept="image/*" id="id_reference_image1">
  </div>

  <div class="mb-3">
    <label class="form-label" for="id_reference_image2">参考画像2</label>
    <input class="form-control" type="file" name="reference_image2" accept="image/*" id="id_reference_image2">
  </div>

  <div class="mb-3">
    <label class="form-label" for="id_reference_image3">参考画像3</label>
    <input class="form-control" type="file" name="reference_image3" accept="image/*" id="id_reference_image3">
  </div>

  <div class="mb-3">
    <label class="form-label" for="id_reference_movie1">参考動画1</label>
    <input class="form-control" type="file" name="reference_movie1" id="id_reference_movie1">
  </div>

  <div class="mb-3">
    <label class="form-label" for="id_reference_movie2">参考動画2</label>
    <input class="form-control" type="file" name="reference_movie2" id="id_reference_movie2">
  </div>

  <div class="mb-3">
    <label class="form-label" for="id_reference_movie3">参考動画3</label>
    <input class="form-control" type="file" name="reference_movie3" id="id_reference_movie3">
  </div>

  <div class="mb-3">
    <label class="form-label" for="id_reference_music1">参考音源1</label>
    <input class="form-control" type="file" name="reference_music1" id="id_reference_music1">
  </div>

  <div class="mb-3">
    <label class="form-label" for="id_reference_music2">参考音源2</label>
    <input class="form-control" type="file" name="reference_music2" id="id_reference_music2">
  </div>

  <div class="mb-3">
    <label class="form-label" for="id_reference_music3">参考音源3</label>
    <input class="form-control" type="file" name="reference_music3" id="id_reference_music3">
  </div>

  <div class="mb-3">
    <label class="form-label" for="id_reference_url1">参考URL1</label>
    <input class="form-control" type="url" name="reference_url1" maxlength="200" id="id_reference_url1">
  </div>

  <div class="mb-3">
    <label class="form-label" for="id_reference_url2">参考URL2</label>
    <input class="form-control" type="url" name="reference_url2" maxlength="200" id="id_reference_url2">
  </div>

  <div class="mb-3">
    <label class="form-label" for="id_reference_url3">参考URL3</label>
    <input class="form-control" type="url" name="reference_url3" maxlength="200" id="id_reference_url3">
  </div>



  
    
    
  </div> {% endcomment %}

  <button type="submit" class="btn btn-primary">作成する</button>
</form>


</div>

{% endblock %}