account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "account"

urlpatterns = [
    path(
        "signup/",
        views.SignUpView.as_view(),
        name="signup"
    ),
    path(
        "signup-success/",
        views.SignUpSuccessView.as_view(),
        name="signup_success"
    ),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="login.html"),
        name="login"
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="logout.html"),
        name="logout"
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="logout.html"),
        name="logout"
    ),
    path(
        "user-data/<int:pk>",
        views.UserUpdate.as_view(),
        name="user_update"
    ),
    path(
        "profile/",
        views.UserDetailCreate.as_view(),
        name="create_feedback_rule"
    ),
    path(
        "profile/<int:detail_num>",
        views.UserDetailCreate.as_view(),
        name="create_feedback_rule"
    ),
    path(
        "profile-edit/<int:pk>",
        views.UserDetailUpdate.as_view(),
        name="update_feedback_rule"
    ),
    path(
        "mypage/<int:pk>",
        views.CustomUserDetailView.as_view(),
        name="mypage"
    ),
    
]

good_feedback/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("project.urls")),
    path("account/", include("account.urls")),
    path("feedback/", include("feedback.urls")),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

project/urls.py
from django.urls import path

from . import views

app_name = "project"

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('new-project-create/', views.CreateProjectView.as_view(), name="create_project"),
    path('new-project-propose/<int:pk>', views.ProposeProjectView.as_view(), name="propose_project"),
    path('new-project/feedback-set/<int:pk>', views.SetFeedbackView.as_view(), name="feedback_set"),
    path('project-list/', views.ProjectListView.as_view(), name="project_list"),
    path('project/<int:pk>', views.ProjectDetailView.as_view(), name="project_detail"),
    path('new-project/<int:pk>', views.CreateProjectSuccessView.as_view(), name="create_project_done"),
    path('project-update/<int:pk>', views.ProjectUpdateView.as_view(), name="project_update"),
    path('project-done/<int:pk>', views.ProjectDoneView.as_view(), name="project_done"),
    path('project-finish', views.ProjectDoneSuccessView.as_view(), name="project_done_success"),
    path('add-task/<int:pk>', views.AddTaskView.as_view(), name="add_task"),
    path('task-list/<int:pk>', views.TaskListView.as_view(), name="task_list"),
    path('task-detail/<int:pk>', views.TaskDetailView.as_view(), name="task_detail"),
    path('task-edit/<int:pk>', views.TaskEditView.as_view(), name="task_edit"),
    path('task-delete/<int:pk>', views.TaskDeleteView.as_view(), name="task_delete"),
    path('add-todo/<int:pk>/<int:project_id>', views.ToDoCreateView.as_view(), name="add_todo"),
    path('todo-check/<int:pk>', views.ToDoDoneView.as_view(), name="todo_checked"),
    # path('todo-delete/<int:pk>', views.ToDoDeleteView.as_view(), name="todo_delete"),

    path('todo-done/<int:pk>', views.todo_done, name="todo_done"),
    path('todo-delete/<int:pk>', views.todo_delete, name="todo_delete"),

    path('about', views.AboutUsView.as_view(), name="about_us"),
    # path('project/<int:pk>/done', views.done_todo, name="done_todo"),
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser



class CustomUser(AbstractUser):
    pass


class UserDetail(models.Model):
    profile = models.TextField(
        verbose_name="仕事内容"
    )
    rule = models.TextField(
        verbose_name="仕事の進め方やお願い"
    )
    convenient_time_from = models.TimeField(
        verbose_name="都合の良い時間帯の開始時刻",
        # auto_now_add=False  # ここないからエラー出るかも？
    )
    convenient_time_to = models.TimeField(
        verbose_name="都合の良い時間帯の終了時刻",
        # auto_now_add=False  # ここないからエラー出るかも？
    )

    CONTACT = (
        ("tel", "電話"),
        ("mail", "メール"),
        ("line", "ライン"),
        ("skype", "スカイプ"),
    )

    how_to_contact = models.CharField(
        verbose_name="連絡手段",
        max_length=50,
        choices=CONTACT
    )
    user = models.ForeignKey(
        CustomUser,
        verbose_name="ユーザー",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )

    LABEL = (
        ("ルール1", "ルール1"),
        ("ルール2", "ルール2"),
        ("ルール3", "ルール3"),

    )

    label_select = models.CharField(
        verbose_name="ラベル",
        max_length=50,
        choices=LABEL
    )

    def __str__(self):
        return self.label_select

account/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm





from .models import CustomUser, UserDetail

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("username", "last_name", "first_name", "email", "password1", "password2")
        # fields = "__all__"
        # lastnameは苗字

class UserDetailForm(ModelForm):
    class Meta:
        model = UserDetail
        fields = (
            "label_select",
            "profile",
            "rule",
            "convenient_time_from",
            "convenient_time_to",
            "how_to_contact",
        )

account/views.py
from django.views.generic import CreateView, TemplateView, DetailView, UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView


from .forms import CustomUserCreationForm, UserDetailForm
from .models import CustomUser, UserDetail

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    template_name = "signup.html"
    success_url = reverse_lazy("account:signup_success")

    def form_valid(self, form):
        user = form.save()
        self.object = user
        print(self.object)
        print(self.object.username)
        print(self.request.session)
        if not 'new_user' in self.request.session:
            self.request.session['new_user'] = self.object.username
        print(self.request.session['new_user'])

        return super().form_valid(form)

class SignUpSuccessView(LoginView):
    template_name = "signup_success.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'new_user' in self.request.session:
            print(self.request.session['new_user'])
            context["new_user"] = self.request.session['new_user']
            del self.request.session['new_user']
            print('new_user' in self.request.session)
        else:
            # context["new_user"] = ""
            pass
        


        return context
    


class UserUpdate(UpdateView):
    model = CustomUser
    fields = (
        "username",
        "last_name",
        "first_name",
        "email",
    )

    template_name = "user_update.html"
    success_url = reverse_lazy("project:index")
    
    def get_success_url(self):
        return reverse_lazy("account:mypage", kwargs={"pk": self.request.user.id})


    def form_valid(self, form):
        user_update = form.save(commit=False)
        user_update.user = self.request.user
        user_update.save()
        # user_detail1 = CustomUser.save(commit=False)
        # user_detail1.detail1 = UserDetail.objects.get()
        return super().form_valid(form)


class UserDetailCreate(CreateView):
    form_class = UserDetailForm
    template_name = "create_feedback_rule.html"
    
    def get_success_url(self):
        return reverse_lazy("account:mypage", kwargs={"pk": self.request.user.id})


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["button_message"] = "登録する"
        if "detail_num" in self.kwargs:
            num = self.kwargs["detail_num"]
            str_num = str(num)
            context["detail_num"] = "detail" + str_num
        else:
            pass
        return context
    


    def form_valid(self, form):
        detail = form.save(commit=False)
        detail.user = self.request.user
        detail.save()
        # user_detail1 = CustomUser.save(commit=False)
        # user_detail1.detail1 = UserDetail.objects.get()
        return super().form_valid(form)
    

class UserDetailUpdate(UpdateView):
    model = UserDetail
    form_class = UserDetailForm
    template_name = "create_feedback_rule.html"
    
    def get_success_url(self):
        return reverse_lazy("account:mypage", kwargs={"pk": self.request.user.id})


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["button_message"] = "更新する"
        return context

    def form_valid(self, form):
        detail = form.save(commit=False)
        detail.user = self.request.user
        detail.save()
        for f in form:
            print(f.name)
        # user_detail1 = CustomUser.save(commit=False)
        # user_detail1.detail1 = UserDetail.objects.get()
        return super().form_valid(form)
    



class CustomUserDetailView(DetailView):
    model = CustomUser
    template_name = "mypage.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["details"] = UserDetail.objects.filter(user=self.request.user)
        context["mypage"] = True
        print(context["details"])
        return context
    

account/templates/create_feedback_rule.html
{% extends "base.html" %}
{% load widget_tweaks %}


{% block contents %}


<div class="container">
  <div class="d-flex border-bottom mb-2">
    <h5 class="mb-1">
      {{request.user}}さんのフィードバック
    </h5>
  </div>

  <form action="" method="post">
  {% csrf_token %}
  {% for field in form %}
    {% if field == form.label_select %}
      {% if detail_num %}
      <div class="mb-3">
        {% comment %} <label class="form-label" for="id_label_select">ラベル</label> {% endcomment %}
        <select name="label_select" class="form-control shadow-none"  id="id_label_select" disabled>
          <option value="detail0" {% if detail_num == "detail0" %}selected=""{% endif %}>ルール1</option>
          <option value="detail1" {% if detail_num == "detail1" %}selected=""{% endif %}>ルール2</option>
          <option value="detail2" {% if detail_num == "detail2" %}selected=""{% endif %}>ルール3</option>
        </select>
        <input type="hidden" name="label_select" value="{{detail_num}}">
      </div> 
      {% elif field.value %}
        {{field.as_hidden}}
      <div class="mb-3">
        {% comment %} <label class="form-label" for="{{field.id_for_label}}">{{field.label}}</label> {% endcomment %}
        {% render_field field class="form-control shadow-none" disabled="" %}
        {{field.errors}}
        {% for error in field.errors %}
        <p>{{error}}</p>
        {% endfor %}
        {% comment %} {{field.value}} {% endcomment %}
      </div>
      {% else %}
      <div class="mb-3">
        {% comment %} <label class="form-label" for="id_label_select">ラベル</label> {% endcomment %}
        <select name="label_select" class="form-control shadow-none"  id="id_label_select" disabled>
          <option value="detail0" selected="">プロフィール1(デフォルト)</option>
        </select>
        <input type="hidden" name="label_select" value="detail0">
      </div> 
      {% endif %}

    {% else %}
    <div class="mb-3">
      <label class="form-label" for="{{field.id_for_label}}">{{field.label}}</label>
      {% render_field field class="form-control" %}
      {{field.errors}}
      {% for error in field.errors %}
      <p>{{error}}</p>
      {% endfor %}
    </div>

    {% endif %}

  {% endfor %}
  
    <button type="submit" class="btn btn-primary">{{button_message}}</button>
    
  </form>

</div>



{% endblock %}

account/templates/login.html
{% extends "base.html" %}

{% block contents %}


<div class="container text-center">

  <h3>ログイン</h3>

  
  <form method="post">
    {% csrf_token %}
    <div class="row mb-3">
      <label for="Username" class="col-sm-2 col-form-label">
        ユーザーID</label>
      <!-- name属性の値はLoginViewで定義されているフィールド名username -->
      <div class="col-sm-10">
        <input type="text"
          name="username"
          id="id_username"
          maxlength="150"
          autocapitalize="none"
          autocomplete="username"
          class="form-control"
          placeholder="ユーザー名"
          required autofocus>
      </div>
    </div>

    <div class="row mb-3">
      <label for="Password" class="col-sm-2 col-form-label">
        パスワード</label>
        <!-- name属性の値はLoginViewで定義されているフィールド名password -->
      <div class="col-sm-10">

        <input type="password"
          name="password"
          id="id_password"
          autocomplete="current-password"
          class="form-control"
          placeholder="パスワード"
          required autofocus>
      </div>
    </div>

    <button type="submit" class="btn btn-primary">ログイン</button>

    <input type="hidden"
      name="next"
      value="{% url 'project:index' %}">
  </form>
</div>



{% endblock contents %}


account/templates/logout.html


<h3>ログアウトしました</h3>

<p><a href="{% url "project:index" %}">トップページへ戻る</a></p>

account/templates/mypage.html
{% extends "base.html" %}

{% block contents %}

<div class="container">
  <div class="d-flex border-bottom mb-3">
    <h5 class="mb-1">
      {% if request.user.last_name %}
      {{request.user.last_name}}{% else %}{{request.user}}{% endif %}さんのプロフィール
    </h5>
    <a href="{% url "account:user_update" request.user.pk %}" class="ms-3">編集する</a>
  </div>

  <div class="card py-3 pb-2 px-3 mb-4">
    <div class="row mb-3">
      <div class="col-sm-3">お名前</div>
      {% if object.last_name or object.first_name %}
      <div class="col-sm-6">{{object.last_name}}　{{object.first_name}}</div>
      {% else %}
      <div class="col-sm-6">登録されていません</div>
      {% endif %}
    </div>

    <div class="row mb-2">
      <div class="col-sm-3">メールアドレス</div>
      {% if object.email %}
      <div class="col-sm-6">{{object.email}}</div>
      {% else %}
      <div class="col-sm-6">登録されていません</div>
      {% endif %}
    </div>
  </div>

  <div class="d-flex border-bottom mb-3">
    <h5 class="mb-1">
      フィードバックルール
    </h5>
    {% comment %} <p class="text-secondary">フィードバックルールは3つまで設定できます</p> {% endcomment %}

  </div>

  {% if details %}
  <ul class="nav nav-tabs" id="myTab" role="tablist">
  {% for detail in details %}
    <li class="nav-item" role="presentation">
      <button 
    {% if forloop.first %}
      class="nav-link active" aria-selected="true"
    {% else %}
      class="nav-link" aria-selected="false"
    {% endif %}
      id="{{detail.label_select}}-tab" data-bs-toggle="tab" data-bs-target="#{{detail.label_select}}-tab-pane" type="button" role="tab" aria-controls="{{detail.label_select}}-tab-pane" >ルール{{forloop.counter}}</button>
    </li>
    {% if forloop.last and forloop.counter != 3 %}
    <li class="nav-item" role="presentation">
      <button class="nav-link bg-primary" onclick="location.href='{% url "account:create_feedback_rule" forloop.counter %}'" type="button" role="tab"><strong class="text-white">＋ルールを追加する</strong></button>
  </li>
    
    {% endif %}
  {% endfor %}
  </ul>



  <div class="tab-content bg-white py-3 pb-2 px-3  border border-top-0 rounded-bottom shadow-sm" id="myTabContent">
  {% for detail in details %}
    {% if forloop.first %}


    <div class="tab-pane fade show active" id="{{detail.label_select}}-tab-pane" role="tabpanel" aria-labelledby="{{detail.label_select}}-tab" tabindex="0">
      <p>{{detail.profile}}</p>
      <p>{{detail.rule}}</p>
      <a href="{% url "account:update_feedback_rule" detail.pk %}">編集する</a>

    </div>
    {% else %}
    <div class="tab-pane fade" id="{{detail.label_select}}-tab-pane" role="tabpanel" aria-labelledby="{{detail.label_select}}-tab" tabindex="0">
      <p>{{detail.profile}}</p>
      <p>{{detail.rule}}</p>
      <a href="{% url "account:update_feedback_rule" detail.pk %}">編集する</a>

    </div>
    {% endif %}
    {% comment %} <div class="tab-pane fade" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab" tabindex="0">...</div>
    <div class="tab-pane fade" id="contact-tab-pane" role="tabpanel" aria-labelledby="contact-tab" tabindex="0">...</div>
    <div class="tab-pane fade" id="disabled-tab-pane" role="tabpanel" aria-labelledby="disabled-tab" tabindex="0">...</div> {% endcomment %}
  {% endfor %}

  </div>
  

  {% else %}
  <p>まだ登録されていません。</p>
  <a href="{% url "account:create_feedback_rule" %}">登録はこちら</a>
  
  {% endif %}
  






</div>





{% endblock %}

account/templates/signup.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block contents %}

<div class="container">
  <h3>新規登録</h3>

  <form method="post">
    {% csrf_token %}

    <div class="row mb-3">
      <label class="col-sm-2 col-form-label" for="{{form.username.id_for_label}}">ユーザーID</label>
      <div class="col-sm-10">

        {% render_field form.username class="form-control" %}
      </div>
      {% if form.username.help_text %}
      <div class="form-text offset-sm-2">{{ form.username.help_text }}</div>
      {% endif %}
      {% for error in form.username.errors %}
      <p style="color: red;">{{ error }}</p>
      {% endfor %}
    </div>


    <div class="row mb-3">
      <label class="col-sm-2 col-form-label" for="">お名前</label>
      <div class="col">
        {% comment %} <label class="col-sm-2 col-form-label" for="">{{form.last_name.label}}</label> {% endcomment %}
        <div class="">
  
          {% render_field form.last_name class="form-control" %}
        </div>
        {% if form.last_name.help_text %}
        <div class="form-text">{{ form.last_name.help_text }}</div>
        {% endif %}
        {% for error in form.last_name.errors %}
        <p style="color: red;">{{ error }}</p>
        {% endfor %}
      </div>
      <div class="col">
        {% comment %} <label class="col-sm-2 col-form-label" for="{{form.first_name.id_for_label}}">{{form.first_name.label}}</label> {% endcomment %}
        <div class="">
          {% render_field form.first_name class="form-control" %}
        </div>
        {% if form.first_name.help_text %}
        <div class="form-text">{{ form.first_name.help_text }}</div>
        {% endif %}
        {% for error in form.first_name.errors %}
        <p style="color: red;">{{ error }}</p>
        {% endfor %}
      </div>
    </div>



    <div class="row mb-3">
      <label class="col-sm-2 col-form-label" for="{{form.email.id_for_label}}">{{form.email.label}}</label>
      <div class="col-sm-10">

        {% render_field form.email class="form-control" required="required" %}
      </div>
      {% if form.email.help_text %}
      <div class="form-text">{{ form.email.help_text }}</div>
      {% endif %}
      <div class="form-text offset-sm-2">※メールアドレスはパスワードをリセットする際に必要になりますので、登録をお願いします。</div>
      {% for error in form.email.errors %}
      <p style="color: red;">{{ error }}</p>
      {% endfor %}
    </div>
    <div class="row mb-3">
      <label class="col-sm-2 col-form-label" for="{{form.password1.id_for_label}}">{{form.password1.label}}</label>
      <div class="col-sm-10">

        {% render_field form.password1 class="form-control" %}
      </div>
      {% if form.password1.help_text %}
      <div class="form-text offset-sm-2">{{ form.password1.help_text }}</div>
      {% endif %}
      {% for error in form.password1.errors %}
      <p style="color: red;">{{ error }}</p>
      {% endfor %}
    </div>
    <div class="row mb-3">
      <label class="col-sm-2 col-form-label" for="{{form.password2.id_for_label}}">パスワード:確認用</label>
      <div class="col-sm-10">

        {% render_field form.password2 class="form-control" %}
      </div>
      {% if form.password2.help_text %}
      <div class="form-text offset-sm-2">{{ form.password2.help_text }}</div>
      {% endif %}
      {% for error in form.password2.errors %}
      <p style="color: red;">{{ error }}</p>
      {% endfor %}
    </div>

    <button type="submit" class="btn btn-primary">新規登録</button>

  </form>




  <br>
  <p><a href="{% url "project:index" %}">
    登録をやめてトップページに戻る</a>
  </p>


</div>

{% endblock %}

account/templates/signup_success.html
{% extends "base.html" %}

{% block contents %}

<div class="container">

  <h3>ようこそ！</h3>
  
  <p>登録が完了しました！</p>
  <p>確認のため、パスワードを入力してログインをしてください</p>
  


  <form method="post">
    {% csrf_token %}
    <div class="row mb-3">
      <label for="Username" class="col-sm-2 col-form-label">
        ユーザーID</label>
      <!-- name属性の値はLoginViewで定義されているフィールド名username -->
      <div class="col-sm-10">
        <input type="text"
          name="username"
          id="id_username"
          maxlength="150"
          autocapitalize="none"
          autocomplete="username"
          class="form-control"
          placeholder="お手数ですがユーザーIDの再入力をお願いします。"
          value="{{new_user}}"
          required>
      </div>
    </div>

    <div class="row mb-3">
      <label for="Password" class="col-sm-2 col-form-label">
        パスワード</label>
        <!-- name属性の値はLoginViewで定義されているフィールド名password -->
      <div class="col-sm-10">

        <input type="password"
          name="password"
          id="id_password"
          autocomplete="current-password"
          class="form-control"
          placeholder="パスワード"
          required autofocus>
      </div>
    </div>

    <button type="submit" class="btn btn-primary">ログインして始める！</button>

    <input type="hidden"
      name="next"
      value="{% url 'project:index' %}">
  </form>



  <p><a href="{% url "account:login" %}">ログインはこちら</a></p>

</div>

{% endblock %}

account/templates/user_update.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block contents %}

<div class="container">
  <div class="d-flex border-bottom mb-3">
    <h5 class="mb-1">
      ユーザー情報の変更
    </h5>
  </div>

  <form method="post">
    {% csrf_token %}

    <div class="row mb-3">
      <label class="col-sm-3 col-form-label" for="{{form.username.id_for_label}}">ユーザーID</label>
      <div class="col-sm-9">

        {% render_field form.username class="form-control" %}
      </div>
      <div class="form-text offset-sm-3">ユーザーIDを変更される場合は、一緒にお仕事されている方にもご連絡をお願いします。</div>
      {% for error in form.username.errors %}
      <p style="color: red;">{{ error }}</p>
      {% endfor %}
    </div>


    <div class="row mb-3">
      <label class="col-sm-3 col-form-label" for="">お名前</label>
      <div class="col">
        <div class="">
          {% render_field form.last_name class="form-control" %}
        </div>
        {% if form.last_name.help_text %}
        <div class="form-text">{{ form.last_name.help_text }}</div>
        {% endif %}
        {% for error in form.last_name.errors %}
        <p style="color: red;">{{ error }}</p>
        {% endfor %}
      </div>
      <div class="col">
        <div class="">
          {% render_field form.first_name class="form-control" %}
        </div>
        {% if form.first_name.help_text %}
        <div class="form-text">{{ form.first_name.help_text }}</div>
        {% endif %}
        {% for error in form.first_name.errors %}
        <p style="color: red;">{{ error }}</p>
        {% endfor %}
      </div>
    </div>



    <div class="row mb-3">
      <label class="col-sm-3 col-form-label" for="{{form.email.id_for_label}}">{{form.email.label}}</label>
      <div class="col-sm-9">

        {% render_field form.email class="form-control" required="required" %}
      </div>
      {% if form.email.help_text %}
      <div class="form-text">{{ form.email.help_text }}</div>
      {% endif %}
      <div class="form-text offset-sm-3"></div>
      {% for error in form.email.errors %}
      <p style="color: red;">{{ error }}</p>
      {% endfor %}
    </div>
    <button type="submit" class="btn btn-primary">更新する</button>

  </form>




  <br>
  <p><a href="{% url "account:mypage" request.user.pk %}">
    編集をやめてマイページに戻る</a>
  </p>


</div>

{% endblock %}